project:
  type: website
website:
  title: "jkrumbiegel.com"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jkrumbiegel
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto
