project:
  type: website
website:
  title: "jkrumbiegel.com"
  site-url: https://jkrumbiegel.com
  description: "Programming, data visualization and data science with Julia."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jkrumbiegel
format:
  html:
    theme: flatly
    css: styles.css
execute:
  freeze: auto
filters:
  - terminal_html.lua
  - quarto
